NPROC_PER_NODE=4 \
CUDA_VISIBLE_DEVICES=0,1,2,3 \
swift rlhf \
    --rlhf_type grpo \
    --model /mnt/hdfs/if_au/data/avqa_reason/checkpoint-948-merged \
    --reward_funcs evidence_driven_format answer_exact_match perception_judge_vllm cot_quality_judge_vllm \
    --reward_weights 0.1 1.5 1.5 1 \
    --train_type lora \
    --lora_rank 32 \
    --lora_alpha 64 \
    --target_modules all-linear \
    --torch_dtype bfloat16 \
    --dataset "/mnt/hdfs/if_au/data/avqa_reason/RL_46544/avqa_RL_46544_format_path.json" \
    --load_from_cache_file true \
    --external_plugins "/opt/tiger/hqz_debug/mrx/R1-AL/examples/train/grpo/plugin/plugin.py" \
    --max_completion_length 2048 \
    --num_train_epochs 1 \
    --max_steps 5000 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --learning_rate 1e-5 \
    --gradient_accumulation_steps 1 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 100 \
    --logging_steps 5 \
    --max_length 2048 \
    --output_dir output_step_reason_4K6_R1234 \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --dataset_num_proc 4 \
    --num_generations 8 \
    --temperature 1. \
    --top_p 0.99 \
    --top_k 50 \
    --system '/opt/tiger/hqz_debug/mrx/R1-AL/examples/train/grpo/prompt.txt' \
    --deepspeed zero2 \
    --log_completions true